### ISSUE TITLE
no new nodes when keys are pressed

### ISSUE THREAD

**Issue by SiliconLion** [SiliconLion/schoolMap#9] opened 2018-01-21 04:33 UTC
there are several keys that we watch for, that produce actions depending on whether they are held over another node or not. however, when the mouse is clicked over where there is a node or not, there is always a new node created. we do not want any new nodes created when there that we watch for being held down

**Comment by SmithSAC** [comment] 2018-01-25 17:18
This is a duplicate of the node creation when pressing x issue. This has been solved with a pull request that is pending as of 1/25/2018

**Closed as completed by SmithSAC** 2018-01-25 17:18 UTC
